FROM duluca/minimal-node-build-env:8.11.2 as builder

# project variables
ENV SRC_DIR /usr/src
ENV GIT_REPO https://github.com/mxm1512/m-square-ht.git
ENV BUILD_SCRIPT build:prod

# get source code
RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR
# if necessary, do SSH setup here or copy source code from local or CI environment
ARG CACHEBUST=1
RUN git clone $GIT_REPO .

RUN npm ci
RUN npm run $BUILD_SCRIPT
